# -*- coding: utf-8 -*-
"""Copy of proj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ymqqiliu19UHHZn-yscdgs8LPUyLondZ

## Exercice 1
On se place sur $X = {\mathbf{R}}^3_+$ et on considère la relation de préférence notée $\preccurlyeq$ définie comme suit : 
$(x_1,x_2,x_3) \preccurlyeq (y_1,y_2,y_3)$ si et seulement pour au moins deux valeurs de $i$ dans $\{1, 2, 3\}$ on a $x_i \leq y_i$.

### 1.1
Montrer cette relation de préférence est complète.

### 1.2
À l'aide d'un contrexemple, montrer que cette relation de préférence n'est pas transitive.

## Réponses Exercice 1

## 1.1
Une relation de préférence est complète lorsque pour tous les paniers de consommation A et B, le consommateur est toujours capable de dire s'il préfère A à B ou B à A ou si A et B sont équivalents.

Ici on a la relation $(x_1,x_2,x_3) \preccurlyeq (y_1,y_2,y_3)$ si pour au moins deux valeurs de $i$ dans $\{1, 2, 3\}$ on a $x_i \leq y_i$. Ce qui signifie que au moins deux éléments du panier $(y_1,y_2,y_3)$ sont préférés ou équivalents à au moins deux des éléments du panier $(x_1,x_2,x_3)$. Étant donné que chaque panier a trois éléments, cela implique que le consommateur est toujours capable de faire un choix quand les deux paniers s'offrent à lui. Par conséquent cette relation de préférence est complète.

## 1.2
Une relation de préférence est transitive lorsque si le panier A est préféré ou indifférent au panier B et si le panier B est préféré ou indifférent au panier C, alors le panier A est préféré ou indifférent au panier C. Mathématiquement, cela induit à écrire $A\geq B$, $B\geq C$, donc $A\geq C$.

***Contrexemple*** : soit $X=(1,3,2)$, $Y=(2,1,3)$, $Z=(3,2,1)$.

On a $X \preccurlyeq Y$ car $x_1 < y_1$ et $x_3 < y_3$ ;

On a $Y \preccurlyeq Z$ car $y_1 < z_1$ et $y_2 < z_2$ ;

Mais on a cependant $X\geq Z$ car $x_2 > z_2$ et $x_3 > z_3$.

On appelle ce type de paradoxe un "**Paradoxe de Condorcet**".

## Exercice 2B
### 2.1
Discuter du maximum de la fonction d'utilité $U(x,y)=2x^3 + x^2 y - 9x^2 - 2xy + 2x - 4y + 20$ sous les contraintes $x\geq 0$, $y\geq 0$ et la contrainte de revenu $5x+3y\leq r$ pour $r=5$ puis pour $r=20$.
Vérifier avec un dessin du graphe de $U$.

### 2.2
Soit $U:(x,y)\mapsto U(x,y)$ une fonction d'utilité (à valeurs dans $\mathbf{R}$) dont on cherche le maximum sous les contraintes conjointes $c_1(x,y)\leq 0$, $c_2(x,y)\leq 0$ et $c_3(x,y)\leq 0$. On ne précise ni $U$ ni les $c_i$.
On a exécuté avec Sagemath la suite d'instructions ci-dessous et obtenu la réponse qui suit. Que peut on dire des couples $(x,y)$ où $U$ est maximal ? Expliquer.
Que peut on dire des couples $(x,y)$ où $U$ est minimal ?

```python
var('l,m,n')
L = (U-l*c1-m*c2-n*c3).gradient()(x,y)
S = solve([L[0]==0,L[1]==0,l*c1==0,m*c2==0,n*c3==0],[x,y,l,m,n])

print '(x,y), (l,m,n), (c1(x,y),c2(x,y),c3(x,y)) ='
ns = 1
for s in S:
    x,y,l,m,n = (s[i].rhs().n(digits=2) for i in range(5))
    print ns,(x,y),(l,m,n),(c1(x,y),c2(x,y),c3(x,y))
    ns = ns+1

(x,y), (l,m,n), (c1(x,y),c2(x,y),c3(x,y)) =
1 (1.0, -2.0) (0.00, 0.00, 0.00) (-1.0, 2.0, -11.)  
2 (0.00, -1.0) (-2.0, 0.00, 0.00) (0.00, 1.0, -10.)  
3 (0.00, 0.00) (-4.0, -2.0, 0.00) (0.00, 0.00, -5.0)  
4 (1.5, -0.17) (0.00, 0.00, 0.92) (-1.5, 0.17, 0.00)  
5 (0.00, 1.0) (-2.8, 0.00, 0.80) (0.00, -1.0, 0.00)  
6 (1.2, 0.00) (0.00, 0.50, 1.0) (-1.2, 0.00, 0.00)  
```

## Exercice 3B
On considère le jeu de poker simplifié à deux joueurs suivant. Trois mains sont possibles, numérotées de $1$ à $3$, de la plus faible à la plus forte. Chaque joueuse, ayant reçu l'une de ces mains, met un jeton au pot. Le jeu se déroule ensuite selon le schéma ci-dessous (jeu séquentiel), sachant que, pour _miser_ ou pour _voir_, une joueuse doit rajouter un jeton au pot (rien à mettre au pot si la joueuse choisit de _passer_). La gagnante remporte le pot. 
La joueuse 2 triche et, à l'insu de la joueuse 1, s'est arrangée avec le croupier qui distribue les cartes afin que la main $(1, 3)$ (qui lui est favorable) sorte plus souvent que les autres, avec une probabilité de $1/4$ (les cinq autres mains sortant avec une même probabilité de $3/20$).

![Règles du jeu](https://github.com/jbcaillau/ande/blob/master/proj/poker.png?raw=1)

### 3.1
Calculer la matrice des gains (en espérance) du jeu sous forme normale.

### 3.2
Déterminer les stratégies _prudentes_ de chaque joueuse, c'est à dire la stratégie $\max_i \min_j$ pour la joueuse 1 et $\min_j \max_i$ de la joueuse 2. Y a-t-il équilibre (en stratégies pures) ?

### 3.3
Déterminer les éventuelles stratégies dominées de chaque joueuse.

### 3.4
Déterminer la valeur du jeu en stratégies mixtes, et donner un couple de stratégies mixtes en équilibre.

### 3.5
Un nouveau croupier remplace le précédent. Quatre mains sont désormais possibles, numérotées de $1$ à $4$, de la plus faible à la plus forte. Donner l'ensemble des stratégies (pures) pour chaque joueuse dans le jeu sous forme normale.

### 3.6 (BONUS)
Reprendre les questions 3.1 à 3.5 en supposant le nouveau croupier honnête, de sorte que toutes les combinaisons de mains sont équiprobables.
"""

import numpy as np
from scipy.optimize import linprog

# Exceptions
class StrategieInconnue(Exception):
    """Strategie Inconnue
    
    Attribut :
        s -- stratégie
    """
    def __init__(self, s):
        self.s = s

class MainInconnue(Exception):
    """Main Inconnue
    
    Attribut :
        m -- main
    """
    def __init__(self, m):
        self.m = m

class MainVide(Exception):
    """Main Vide
    """

class PbResolution(Exception):
    """Probleme de resolution du LP
    """

# Stratégies de la joueuse 1
S1m = [ 'M', 'PV', 'PP' ] # M = Mise, P = Passe, V = Voit
l1 = len(S1m)
S1 = [ (S1m[i], S1m[j], S1m[k]) for i in range(0, l1) for j in range(0, l1) for k in range(0, l1) ]
m = len(S1)

# Stratégies de la joueuse 2
S2m = [ 'VP', 'VM', 'PP', 'PM' ] # M = Mise, P = Passe, V = Voit
l2 = len(S2m)
S2 = [ (S2m[i], S2m[j], S2m[k]) for i in range(0, l2) for j in range(0, l2) for k in range(0, l2) ]
n = len(S2)

# Mains pouvant être distribuées
Mains = [ (1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2) ] # main 1 < main 2 < main 3

# Calcul des gains
def gmfun(s1, s2, main):
    """g = gmfun(s1, s2, main)
    Gain de la joueuse 1 en fonction de la main distribuée aux deux joueuses.

    s1 : triplet de stratégies de la joueuse 1
    s2 : triplet de stratégies de la joueuse 2
    main : main (= cartes) distribuées aux joueuses
    """
    if s1 not in S1: raise StrategieInconnue(s1)
    if s2 not in S2: raise StrategieInconnue(s2)
    if main not in Mains: raise MainInconnue(main)

    s1m = s1[main[0]-1]
    s2m = s2[main[1]-1]

    if s1m[0] is 'M': # la joueuse 1 mise

        if s2m[0] is 'V': # la joueuse 2 voit
            if main[0] > main[1]: gm = 2 # la meilleure main emporte le pot
            else: gm = -2
        elif s2m[0] is 'P': # la joueuse 2 passe
            gm = 1 # la joueuse 1 emporte le pot
        else: raise StrategieInconnue(s2)

    elif s1m[0] is 'P': # la joueuse 1 passe

        if s2m[1] is 'P': # la joueuse 2 passe
            if main[0] > main[1]: gm = 1 # la meilleure main emporte le pot
            else: gm = -1
        elif s2m[1] is 'M': # la joueuse 2 mise
            if s1m[1] is 'V': # la joueuse 1 voit
                if main[0] > main[1]: gm = 2 # la meilleure main emporte le pot
                else: gm = -2
            elif s1m[1] is 'P': # la joueuse 1 passe
                gm = -1
            else: raise StrategieInconnue(s1)
        else: raise StrategieInconnue(s2)

    else: raise StrategieInconnue(s1)

    return gm

def gfun(s1, s2):
    """g = gfun(s1, s2)
    Gain en espérance de la joueuse 1 (toutes les mains sont supposées équiprobables)
 
    s1 : triplet de stratégies de la joueuse 1
    s2 : triplet de stratégies de la joueuse 2
    """
    l = len(Mains)
    if l is 0: raise MainVide
    g = 0.
    for i in range(0, l):
        g = g + (1/l) * gmfun(s1, s2, Mains[i])
    return g

A = np.zeros((m, n))
for i in range(0, m):
    for j in range(0, n):
        A[i, j] = gfun(S1[i], S2[j])

d = abs(np.min(A)) + 1
A = A + d # translate les gains pour garantir une valeur > 0 du jeu mixte

# Calcul de la valeur du jeu en stratégies mixtes (minimax)
c =-np.ones(n) # min (c|x) = -max (-c|x)
b = np.ones(m) # Ax <= b 
bounds = (0, None) # 0 <= x

method='simplex'
#method='revised simplex'
#method='interior-point'

res = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method=method)
if not res.success: raise PbResolution

v = 1 / (-res.fun)
x = v * res.x
v = v - d
xx = np.round_(x, decimals=8)

print('v = ', v)
print('x = ', xx)
print('')
print("Stratégie mixte optimale de la joueuse 2 :")
for j in range(0, n):
    if xx[j] > 0:
        print(S2[j], "avec proba", xx[j])